let data = {
  help: "https://data.ontario.ca/api/3/action/help_show?name=datastore_search",
  success: true,
  result: {
    include_total: true,
    resource_id: "8b6d22e2-7065-4b0f-966f-02640be366f2",
    fields: [
      { type: "int", id: "_id" },
      { type: "timestamp", id: "collected_date" },
      { type: "timestamp", id: "reported_date" },
      { type: "text", id: "school_board" },
      { type: "text", id: "school" },
      { type: "text", id: "municipality" },
      { type: "numeric", id: "confirmed_student_cases" },
      { type: "numeric", id: "confirmed_staff_cases" },
      { type: "numeric", id: "confirmed_unspecified_cases" },
      { type: "numeric", id: "total_confirmed_cases" },
    ],
    records_format: "objects",
    records: [
      {
        _id: 1,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École élémentaire catholique Roger-Saint-Denis",
        municipality: "Ottawa",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 2,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École élémentaire catholique Saint-François-d’Assise",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 3,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École élémentaire catholique Sainte-Anne",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 4,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École élémentaire catholique Laurier-Carrière",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 5,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École intermédiaire catholique Franco-Ouest",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 6,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil des écoles publiques de l’Est de l’Ontario",
        school: "École secondaire publique De La Salle",
        municipality: "Ottawa",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 7,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Conseil Scolaire Viamonde",
        school: "École Ronald-Marion",
        municipality: "Pickering",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 8,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Halton Catholic District School Board",
        school: "St. Marguerite d’Youville Catholic Elementary School",
        municipality: "Oakville",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 9,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Halton District School Board",
        school: "Oodeenawi Public School",
        municipality: "Oakville",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 10,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Peel District School Board",
        school: "North Field Office",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 11,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Peel District School Board",
        school: "Ross Drive Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 12,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Peel District School Board",
        school: "Briarwood Public School",
        municipality: "Mississauga",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 13,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        school_board: "Waterloo Region District School Board",
        school: "Edna Staebler Public School",
        municipality: "Waterloo",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },
      {
        _id: 14,
        collected_date: "2020-09-11T00:00:00",
        reported_date: "2020-09-14T00:00:00",
        school_board: "nseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École élémentaire catholique Roger-Saint-Denis",
        municipality: "Ottawa",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: null,
        total_confirmed_cases: 1,
      },

      {
        _id: 100,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Conseil Scolaire Viamonde",
        school: "École Ronald-Marion",
        municipality: "Pickering",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 101,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Dufferin Peel Catholic District School Board",
        school: "St. Joseph Secondary School",
        municipality: "Mississauga",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 102,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Durham District School Board",
        school: "Mapleridge Public School",
        municipality: "Pickering",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 103,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Halton Catholic District School Board",
        school: "St. Marguerite d’Youville Catholic Elementary School",
        municipality: "Oakville",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 104,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Halton District School Board",
        school: "Oodeenawi Public School",
        municipality: "Oakville",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 105,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Briarwood Public School",
        municipality: "Mississauga",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 106,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "John Fraser Secondary School",
        municipality: "Mississauga",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 107,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Louise Arbour Secondary School",
        municipality: "Brampton",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 108,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "North Field Office",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 109,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Ross Drive Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 110,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Ruth Thompson Middle School",
        municipality: "Mississauga",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 111,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Renfrew County District School Board",
        school: "Fellowes High School",
        municipality: "Pembroke",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 3,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 3,
      },
      {
        _id: 112,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Toronto District School Board",
        school: "Bloordale Middle School",
        municipality: "Toronto",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 113,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Toronto District School Board",
        school: "Charles G Fraser Junior Public School",
        municipality: "Toronto",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 114,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Toronto District School Board",
        school: "Don Mills Middle School",
        municipality: "Toronto",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 116,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Waterloo Region District School Board",
        school: "Edna Staebler Public School",
        municipality: "Waterloo",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 117,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "York Region District School Board",
        school: "Little Rouge Public School",
        municipality: "Markham",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 118,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "The Valleys Senior Public School",
        municipality: "Mississauga",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 119,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Toronto District School Board",
        school: "York Mills Collegiate Institute",
        municipality: "Toronto",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 120,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Toronto District School Board",
        school: "Brookhaven Public School",
        municipality: "Toronto",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 121,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school:
          "École élémentaire catholique d'enseignement personnalisé La Source",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 122,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Ottawa Catholic District School Board",
        school: "St Leonard Elementary School",
        municipality: "Ottawa",
        confirmed_student_cases: 2,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 2,
      },
      {
        _id: 123,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Ottawa Catholic District School Board",
        school: "Monsignor Paul Baxter Elementary School",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 124,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Simcoe County District School Board",
        school: "Twin Lakes Secondary School",
        municipality: "Orillia",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 125,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Windsor-Essex Catholic District School Board",
        school: "Stella Maris Catholic Elementary School",
        municipality: "Amherstburg",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 126,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Toronto District School Board",
        school: "School for Experiential Education",
        municipality: "Toronto",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 1,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 127,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Mountain Ash Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 128,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Robert J. Lee Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 129,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "York Region District School Board",
        school: "Blue Willow Public School",
        municipality: "Woodbridge",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 130,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school: "École élémentaire catholique Saint-Rémi",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 131,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Conseil des écoles publiques de l’Est de l’Ontario",
        school: "École secondaire publique Louis-Riel",
        municipality: "Ottawa",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 132,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Ottawa Catholic District School Board",
        school: "Holy Cross Elementary School",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 133,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Ingleborough Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 134,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Tribune Drive Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 135,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "William Parkway Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 136,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Dufferin Peel Catholic District School Board",
        school: "St. Valentine Elementary School",
        municipality: "Mississauga",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 137,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Peel District School Board",
        school: "Eden Rose Public School",
        municipality: "Brampton",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 138,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Dufferin Peel Catholic District School Board",
        school: "St. Raphael Elementary School",
        municipality: "Mississauga",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 2,
        total_confirmed_cases: 2,
      },
      {
        _id: 139,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "York Region District School Board",
        school: "Dr. Roberta Bondar Public School",
        municipality: "Maple",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 140,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "Waterloo Catholic District School Board",
        school: "St Anne Catholic Elementary School ",
        municipality: "Cambridge ",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
      {
        _id: 141,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        school_board: "York Region District School Board",
        school: "Sir Wilfrid Laurier Public School",
        municipality: "Markham",
        confirmed_student_cases: 0,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 1,
        total_confirmed_cases: 1,
      },
      {
        _id: 142,
        collected_date: "2020-09-17T00:00:00",
        reported_date: "2020-09-18T00:00:00",
        school_board: "Conseil des écoles catholiques du Centre-Est (CECCE)",
        school:
          "École élémentaire catholique d'enseignement personnalisé La Source",
        municipality: "Ottawa",
        confirmed_student_cases: 1,
        confirmed_staff_cases: 0,
        confirmed_unspecified_cases: 0,
        total_confirmed_cases: 1,
      },
    ],
    limit: 1000,
    _links: {
      start:
        "/api/3/action/datastore_search?limit=1000&resource_id=8b6d22e2-7065-4b0f-966f-02640be366f2",
      next:
        "/api/3/action/datastore_search?offset=1000&limit=1000&resource_id=8b6d22e2-7065-4b0f-966f-02640be366f2",
    },
    total: 30413,
  },
};

function findMunicipality(array) {
  let arrayLength = array.result.records.length;
  let results = [];
  for (let i = 0; i < arrayLength; i++) {
    results.push(array.result.records[i].municipality);
  }
  return Array.from(new Set(results));
}

function findSchoolBoard(array) {
  let arrayLength = array.result.records.length;
  let results = [];
  for (let i = 0; i < arrayLength; i++) {
    results.push(array.result.records[i].school_board);
  }
  return Array.from(new Set(results));
} //returns array with all the school boards

let schoolBoardctxLabels = [];
let schoolBoardctxData = [];

function countSchoolBoard(array) {
  let arrayLength = array.result.records.length;
  let pulldata = [];
  let sortdata = [];
  let final = [];
  for (let i = 0; i < arrayLength; i++) {
    pulldata.push(array.result.records[i].school_board.trim());
  }

  sortdata = Object.entries(
    pulldata.reduce(
      (prev, curr) => ((prev[curr] = ++prev[curr] || 1), prev),
      {}
    )
  );
  for (let i = 0; i < sortdata.length; i++) {
    final.push({ num: sortdata[i][1], school: sortdata[i][0] });
  }
  schoolBoardctxLabels = final
    .sort((a, b) => b.num - a.num)
    .map((item) => item.school);
  schoolBoardctxData = final
    .sort((a, b) => b.num - a.num)
    .map((item) => item.num);
}
countSchoolBoard(data);

//
//
//

const schoolBoardctx = document
  .getElementById("schoolBoardCases")
  .getContext("2d");
const schooBoardChart = new Chart(schoolBoardctx, {
  type: "horizontalBar",
  data: {
    labels: schoolBoardctxLabels,
    datasets: [
      {
        label: "Cases by School Board",
        backgroundColor: "rgb(255, 99, 132)",
        borderColor: "rgb(255, 99, 132)",
        data: schoolBoardctxData,
      },
    ],
  },
  options: {},
});
