// https://data.ontario.ca/api/3/action/datastore_search?resource_id=7fbdbb48-d074-45d9-93cb-f7de58950418&limit=1000
// set search limit to 1000

const { array } = require("prop-types");

let schoolSummaryData = {
  help: "https://data.ontario.ca/api/3/action/help_show?name=datastore_search",
  success: true,
  result: {
    include_total: true,
    resource_id: "7fbdbb48-d074-45d9-93cb-f7de58950418",
    fields: [
      { type: "int", id: "_id" },
      { type: "timestamp", id: "collected_date" },
      { type: "timestamp", id: "reported_date" },
      { type: "numeric", id: "current_schools_w_cases" },
      { type: "numeric", id: "current_schools_closed" },
      { type: "numeric", id: "current_total_number_schools" },
      { type: "numeric", id: "new_total_school_related_cases" },
      { type: "numeric", id: "new_school_related_student_cases" },
      { type: "numeric", id: "new_school_related_staff_cases" },
      { type: "numeric", id: "new_school_related_unspecified_cases" },
      { type: "numeric", id: "recent_total_school_related_cases" },
      { type: "numeric", id: "recent_school_related_student_cases" },
      { type: "numeric", id: "recent_school_related_staff_cases" },
      { type: "numeric", id: "recent_school_related_unspecified_cases" },
      { type: "numeric", id: "past_total_school_related_cases" },
      { type: "numeric", id: "past_school_related_student_cases" },
      { type: "numeric", id: "past_school_related_staff_cases" },
      { type: "numeric", id: "past_school_related_unspecified_cases" },
      { type: "numeric", id: "cumulative_school_related_cases" },
      { type: "numeric", id: "cumulative_school_related_student_cases" },
      { type: "numeric", id: "cumulative_school_related_staff_cases" },
      { type: "numeric", id: "cumulative_school_related_unspecified_cases" },
    ],
    records_format: "objects",
    records: [
      {
        _id: 1,
        collected_date: "2020-09-10T00:00:00",
        reported_date: "2020-09-11T00:00:00",
        current_schools_w_cases: 13,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 0,
        new_school_related_student_cases: 0,
        new_school_related_staff_cases: 0,
        new_school_related_unspecified_cases: null,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 13,
        cumulative_school_related_student_cases: 4,
        cumulative_school_related_staff_cases: 9,
        cumulative_school_related_unspecified_cases: null,
      },
      {
        _id: 2,
        collected_date: "2020-09-11T00:00:00",
        reported_date: "2020-09-14T00:00:00",
        current_schools_w_cases: 15,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 2,
        new_school_related_student_cases: 1,
        new_school_related_staff_cases: 1,
        new_school_related_unspecified_cases: null,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 15,
        cumulative_school_related_student_cases: 5,
        cumulative_school_related_staff_cases: 10,
        cumulative_school_related_unspecified_cases: null,
      },
      {
        _id: 3,
        collected_date: "2020-09-14T00:00:00",
        reported_date: "2020-09-15T00:00:00",
        current_schools_w_cases: 27,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 14,
        new_school_related_student_cases: 4,
        new_school_related_staff_cases: 4,
        new_school_related_unspecified_cases: 6,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 29,
        cumulative_school_related_student_cases: 9,
        cumulative_school_related_staff_cases: 14,
        cumulative_school_related_unspecified_cases: 6,
      },
      {
        _id: 4,
        collected_date: "2020-09-15T00:00:00",
        reported_date: "2020-09-16T00:00:00",
        current_schools_w_cases: 35,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 12,
        new_school_related_student_cases: 6,
        new_school_related_staff_cases: 4,
        new_school_related_unspecified_cases: 2,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 41,
        cumulative_school_related_student_cases: 15,
        cumulative_school_related_staff_cases: 18,
        cumulative_school_related_unspecified_cases: 8,
      },
      {
        _id: 5,
        collected_date: "2020-09-16T00:00:00",
        reported_date: "2020-09-17T00:00:00",
        current_schools_w_cases: 51,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 21,
        new_school_related_student_cases: 5,
        new_school_related_staff_cases: 4,
        new_school_related_unspecified_cases: 12,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 62,
        cumulative_school_related_student_cases: 20,
        cumulative_school_related_staff_cases: 22,
        cumulative_school_related_unspecified_cases: 20,
      },
      {
        _id: 6,
        collected_date: "2020-09-17T00:00:00",
        reported_date: "2020-09-18T00:00:00",
        current_schools_w_cases: 60,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 11,
        new_school_related_student_cases: 5,
        new_school_related_staff_cases: 0,
        new_school_related_unspecified_cases: 6,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 72,
        cumulative_school_related_student_cases: 25,
        cumulative_school_related_staff_cases: 22,
        cumulative_school_related_unspecified_cases: 25,
      },
      {
        _id: 7,
        collected_date: "2020-09-18T00:00:00",
        reported_date: "2020-09-21T00:00:00",
        current_schools_w_cases: 75,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 18,
        new_school_related_student_cases: 8,
        new_school_related_staff_cases: 4,
        new_school_related_unspecified_cases: 6,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 90,
        cumulative_school_related_student_cases: 33,
        cumulative_school_related_staff_cases: 26,
        cumulative_school_related_unspecified_cases: 31,
      },
      {
        _id: 8,
        collected_date: "2020-09-21T00:00:00",
        reported_date: "2020-09-22T00:00:00",
        current_schools_w_cases: 116,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 51,
        new_school_related_student_cases: 26,
        new_school_related_staff_cases: 7,
        new_school_related_unspecified_cases: 18,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 141,
        cumulative_school_related_student_cases: 59,
        cumulative_school_related_staff_cases: 33,
        cumulative_school_related_unspecified_cases: 49,
      },
      {
        _id: 9,
        collected_date: "2020-09-22T00:00:00",
        reported_date: "2020-09-23T00:00:00",
        current_schools_w_cases: 153,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 42,
        new_school_related_student_cases: 21,
        new_school_related_staff_cases: 5,
        new_school_related_unspecified_cases: 16,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 180,
        cumulative_school_related_student_cases: 77,
        cumulative_school_related_staff_cases: 38,
        cumulative_school_related_unspecified_cases: 65,
      },
      {
        _id: 10,
        collected_date: "2020-09-23T00:00:00",
        reported_date: "2020-09-24T00:00:00",
        current_schools_w_cases: 178,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 31,
        new_school_related_student_cases: 24,
        new_school_related_staff_cases: 3,
        new_school_related_unspecified_cases: 4,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 210,
        cumulative_school_related_student_cases: 101,
        cumulative_school_related_staff_cases: 40,
        cumulative_school_related_unspecified_cases: 69,
      },
      {
        _id: 11,
        collected_date: "2020-09-24T00:00:00",
        reported_date: "2020-09-25T00:00:00",
        current_schools_w_cases: 198,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 29,
        new_school_related_student_cases: 10,
        new_school_related_staff_cases: 10,
        new_school_related_unspecified_cases: 9,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 238,
        cumulative_school_related_student_cases: 110,
        cumulative_school_related_staff_cases: 50,
        cumulative_school_related_unspecified_cases: 78,
      },
      {
        _id: 12,
        collected_date: "2020-09-25T00:00:00",
        reported_date: "2020-09-28T00:00:00",
        current_schools_w_cases: 224,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 36,
        new_school_related_student_cases: 27,
        new_school_related_staff_cases: 3,
        new_school_related_unspecified_cases: 6,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 272,
        cumulative_school_related_student_cases: 137,
        cumulative_school_related_staff_cases: 52,
        cumulative_school_related_unspecified_cases: 83,
      },
      {
        _id: 13,
        collected_date: "2020-09-28T00:00:00",
        reported_date: "2020-09-29T00:00:00",
        current_schools_w_cases: 249,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 63,
        new_school_related_student_cases: 37,
        new_school_related_staff_cases: 7,
        new_school_related_unspecified_cases: 19,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 307,
        cumulative_school_related_student_cases: 164,
        cumulative_school_related_staff_cases: 44,
        cumulative_school_related_unspecified_cases: 99,
      },
      {
        _id: 14,
        collected_date: "2020-09-29T00:00:00",
        reported_date: "2020-09-30T00:00:00",
        current_schools_w_cases: 282,
        current_schools_closed: 3,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 52,
        new_school_related_student_cases: 32,
        new_school_related_staff_cases: 8,
        new_school_related_unspecified_cases: 12,
        recent_total_school_related_cases: null,
        recent_school_related_student_cases: null,
        recent_school_related_staff_cases: null,
        recent_school_related_unspecified_cases: null,
        past_total_school_related_cases: null,
        past_school_related_student_cases: null,
        past_school_related_staff_cases: null,
        past_school_related_unspecified_cases: null,
        cumulative_school_related_cases: 342,
        cumulative_school_related_student_cases: 188,
        cumulative_school_related_staff_cases: 48,
        cumulative_school_related_unspecified_cases: 106,
      },
      {
        _id: 15,
        collected_date: "2020-09-30T00:00:00",
        reported_date: "2020-10-01T00:00:00",
        current_schools_w_cases: 306,
        current_schools_closed: 3,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 64,
        new_school_related_student_cases: 29,
        new_school_related_staff_cases: 14,
        new_school_related_unspecified_cases: 21,
        recent_total_school_related_cases: 386,
        recent_school_related_student_cases: 212,
        recent_school_related_staff_cases: 59,
        recent_school_related_unspecified_cases: 115,
        past_total_school_related_cases: 61,
        past_school_related_student_cases: 21,
        past_school_related_staff_cases: 23,
        past_school_related_unspecified_cases: 17,
        cumulative_school_related_cases: 447,
        cumulative_school_related_student_cases: 233,
        cumulative_school_related_staff_cases: 82,
        cumulative_school_related_unspecified_cases: 132,
      },
      {
        _id: 16,
        collected_date: "2020-10-01T00:00:00",
        reported_date: "2020-10-02T00:00:00",
        current_schools_w_cases: 318,
        current_schools_closed: 3,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 36,
        new_school_related_student_cases: 29,
        new_school_related_staff_cases: 2,
        new_school_related_unspecified_cases: 5,
        recent_total_school_related_cases: 411,
        recent_school_related_student_cases: 236,
        recent_school_related_staff_cases: 61,
        recent_school_related_unspecified_cases: 114,
        past_total_school_related_cases: 72,
        past_school_related_student_cases: 26,
        past_school_related_staff_cases: 23,
        past_school_related_unspecified_cases: 23,
        cumulative_school_related_cases: 483,
        cumulative_school_related_student_cases: 262,
        cumulative_school_related_staff_cases: 84,
        cumulative_school_related_unspecified_cases: 137,
      },
      {
        _id: 17,
        collected_date: "2020-10-02T00:00:00",
        reported_date: "2020-10-05T00:00:00",
        current_schools_w_cases: 335,
        current_schools_closed: 3,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 56,
        new_school_related_student_cases: 31,
        new_school_related_staff_cases: 8,
        new_school_related_unspecified_cases: 17,
        recent_total_school_related_cases: 449,
        recent_school_related_student_cases: 259,
        recent_school_related_staff_cases: 65,
        recent_school_related_unspecified_cases: 125,
        past_total_school_related_cases: 90,
        past_school_related_student_cases: 34,
        past_school_related_staff_cases: 27,
        past_school_related_unspecified_cases: 29,
        cumulative_school_related_cases: 539,
        cumulative_school_related_student_cases: 293,
        cumulative_school_related_staff_cases: 92,
        cumulative_school_related_unspecified_cases: 154,
      },
      {
        _id: 18,
        collected_date: "2020-10-05T00:00:00",
        reported_date: "2020-10-06T00:00:00",
        current_schools_w_cases: 347,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 74,
        new_school_related_student_cases: 41,
        new_school_related_staff_cases: 10,
        new_school_related_unspecified_cases: 23,
        recent_total_school_related_cases: 470,
        recent_school_related_student_cases: 275,
        recent_school_related_staff_cases: 66,
        recent_school_related_unspecified_cases: 129,
        past_total_school_related_cases: 141,
        past_school_related_student_cases: 58,
        past_school_related_staff_cases: 36,
        past_school_related_unspecified_cases: 47,
        cumulative_school_related_cases: 611,
        cumulative_school_related_student_cases: 333,
        cumulative_school_related_staff_cases: 102,
        cumulative_school_related_unspecified_cases: 177,
      },
      {
        _id: 19,
        collected_date: "2020-10-06T00:00:00",
        reported_date: "2020-10-07T00:00:00",
        current_schools_w_cases: 379,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 111,
        new_school_related_student_cases: 69,
        new_school_related_staff_cases: 15,
        new_school_related_unspecified_cases: 27,
        recent_total_school_related_cases: 541,
        recent_school_related_student_cases: 325,
        recent_school_related_staff_cases: 75,
        recent_school_related_unspecified_cases: 141,
        past_total_school_related_cases: 181,
        past_school_related_student_cases: 77,
        past_school_related_staff_cases: 42,
        past_school_related_unspecified_cases: 62,
        cumulative_school_related_cases: 722,
        cumulative_school_related_student_cases: 402,
        cumulative_school_related_staff_cases: 117,
        cumulative_school_related_unspecified_cases: 203,
      },
      {
        _id: 20,
        collected_date: "2020-10-07T00:00:00",
        reported_date: "2020-10-08T00:00:00",
        current_schools_w_cases: 415,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 100,
        new_school_related_student_cases: 51,
        new_school_related_staff_cases: 22,
        new_school_related_unspecified_cases: 27,
        recent_total_school_related_cases: 611,
        recent_school_related_student_cases: 352,
        recent_school_related_staff_cases: 95,
        recent_school_related_unspecified_cases: 164,
        past_total_school_related_cases: 211,
        past_school_related_student_cases: 101,
        past_school_related_staff_cases: 44,
        past_school_related_unspecified_cases: 66,
        cumulative_school_related_cases: 822,
        cumulative_school_related_student_cases: 453,
        cumulative_school_related_staff_cases: 139,
        cumulative_school_related_unspecified_cases: 230,
      },
      {
        _id: 21,
        collected_date: "2020-10-08T00:00:00",
        reported_date: "2020-10-09T00:00:00",
        current_schools_w_cases: 429,
        current_schools_closed: 4,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 56,
        new_school_related_student_cases: 32,
        new_school_related_staff_cases: 9,
        new_school_related_unspecified_cases: 15,
        recent_total_school_related_cases: 628,
        recent_school_related_student_cases: 369,
        recent_school_related_staff_cases: 94,
        recent_school_related_unspecified_cases: 165,
        past_total_school_related_cases: 248,
        past_school_related_student_cases: 113,
        past_school_related_staff_cases: 55,
        past_school_related_unspecified_cases: 80,
        cumulative_school_related_cases: 876,
        cumulative_school_related_student_cases: 482,
        cumulative_school_related_staff_cases: 149,
        cumulative_school_related_unspecified_cases: 245,
      },
      {
        _id: 22,
        collected_date: "2020-10-09T00:00:00",
        reported_date: "2020-10-13T00:00:00",
        current_schools_w_cases: 436,
        current_schools_closed: 3,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 72,
        new_school_related_student_cases: 49,
        new_school_related_staff_cases: 8,
        new_school_related_unspecified_cases: 15,
        recent_total_school_related_cases: 661,
        recent_school_related_student_cases: 390,
        recent_school_related_staff_cases: 100,
        recent_school_related_unspecified_cases: 171,
        past_total_school_related_cases: 287,
        past_school_related_student_cases: 141,
        past_school_related_staff_cases: 57,
        past_school_related_unspecified_cases: 89,
        cumulative_school_related_cases: 948,
        cumulative_school_related_student_cases: 531,
        cumulative_school_related_staff_cases: 157,
        cumulative_school_related_unspecified_cases: 260,
      },
      {
        _id: 23,
        collected_date: "2020-10-13T00:00:00",
        reported_date: "2020-10-14T00:00:00",
        current_schools_w_cases: 421,
        current_schools_closed: 5,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 96,
        new_school_related_student_cases: 51,
        new_school_related_staff_cases: 13,
        new_school_related_unspecified_cases: 32,
        recent_total_school_related_cases: 645,
        recent_school_related_student_cases: 376,
        recent_school_related_staff_cases: 95,
        recent_school_related_unspecified_cases: 174,
        past_total_school_related_cases: 395,
        past_school_related_student_cases: 204,
        past_school_related_staff_cases: 73,
        past_school_related_unspecified_cases: 118,
        cumulative_school_related_cases: 1040,
        cumulative_school_related_student_cases: 580,
        cumulative_school_related_staff_cases: 168,
        cumulative_school_related_unspecified_cases: 292,
      },
      {
        _id: 24,
        collected_date: "2020-10-14T00:00:00",
        reported_date: "2020-10-15T00:00:00",
        current_schools_w_cases: 451,
        current_schools_closed: 5,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 109,
        new_school_related_student_cases: 55,
        new_school_related_staff_cases: 17,
        new_school_related_unspecified_cases: 37,
        recent_total_school_related_cases: 686,
        recent_school_related_student_cases: 399,
        recent_school_related_staff_cases: 99,
        recent_school_related_unspecified_cases: 188,
        past_total_school_related_cases: 459,
        past_school_related_student_cases: 236,
        past_school_related_staff_cases: 85,
        past_school_related_unspecified_cases: 138,
        cumulative_school_related_cases: 1145,
        cumulative_school_related_student_cases: 635,
        cumulative_school_related_staff_cases: 184,
        cumulative_school_related_unspecified_cases: 326,
      },
      {
        _id: 25,
        collected_date: "2020-10-15T00:00:00",
        reported_date: "2020-10-16T00:00:00",
        current_schools_w_cases: 485,
        current_schools_closed: 5,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 98,
        new_school_related_student_cases: 55,
        new_school_related_staff_cases: 12,
        new_school_related_unspecified_cases: 31,
        recent_total_school_related_cases: 735,
        recent_school_related_student_cases: 416,
        recent_school_related_staff_cases: 106,
        recent_school_related_unspecified_cases: 213,
        past_total_school_related_cases: 507,
        past_school_related_student_cases: 274,
        past_school_related_staff_cases: 89,
        past_school_related_unspecified_cases: 144,
        cumulative_school_related_cases: 1242,
        cumulative_school_related_student_cases: 690,
        cumulative_school_related_staff_cases: 195,
        cumulative_school_related_unspecified_cases: 357,
      },
      {
        _id: 26,
        collected_date: "2020-10-16T00:00:00",
        reported_date: "2020-10-19T00:00:00",
        current_schools_w_cases: 483,
        current_schools_closed: 4,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 74,
        new_school_related_student_cases: 48,
        new_school_related_staff_cases: 10,
        new_school_related_unspecified_cases: 16,
        recent_total_school_related_cases: 749,
        recent_school_related_student_cases: 430,
        recent_school_related_staff_cases: 105,
        recent_school_related_unspecified_cases: 212,
        past_total_school_related_cases: 563,
        past_school_related_student_cases: 306,
        past_school_related_staff_cases: 97,
        past_school_related_unspecified_cases: 160,
        cumulative_school_related_cases: 1310,
        cumulative_school_related_student_cases: 736,
        cumulative_school_related_staff_cases: 202,
        cumulative_school_related_unspecified_cases: 372,
      },
      {
        _id: 27,
        collected_date: "2020-10-19T00:00:00",
        reported_date: "2020-10-20T00:00:00",
        current_schools_w_cases: 508,
        current_schools_closed: 4,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 121,
        new_school_related_student_cases: 75,
        new_school_related_staff_cases: 22,
        new_school_related_unspecified_cases: 24,
        recent_total_school_related_cases: 793,
        recent_school_related_student_cases: 461,
        recent_school_related_staff_cases: 117,
        recent_school_related_unspecified_cases: 215,
        past_total_school_related_cases: 636,
        past_school_related_student_cases: 349,
        past_school_related_staff_cases: 106,
        past_school_related_unspecified_cases: 181,
        cumulative_school_related_cases: 1429,
        cumulative_school_related_student_cases: 810,
        cumulative_school_related_staff_cases: 223,
        cumulative_school_related_unspecified_cases: 396,
      },
      {
        _id: 28,
        collected_date: "2020-10-20T00:00:00",
        reported_date: "2020-10-21T00:00:00",
        current_schools_w_cases: 516,
        current_schools_closed: 4,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 144,
        new_school_related_student_cases: 66,
        new_school_related_staff_cases: 13,
        new_school_related_unspecified_cases: 65,
        recent_total_school_related_cases: 823,
        recent_school_related_student_cases: 455,
        recent_school_related_staff_cases: 113,
        recent_school_related_unspecified_cases: 255,
        past_total_school_related_cases: 746,
        past_school_related_student_cases: 419,
        past_school_related_staff_cases: 122,
        past_school_related_unspecified_cases: 205,
        cumulative_school_related_cases: 1569,
        cumulative_school_related_student_cases: 874,
        cumulative_school_related_staff_cases: 235,
        cumulative_school_related_unspecified_cases: 460,
      },
      {
        _id: 29,
        collected_date: "2020-10-21T00:00:00",
        reported_date: "2020-10-22T00:00:00",
        current_schools_w_cases: 501,
        current_schools_closed: 5,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 74,
        new_school_related_student_cases: 49,
        new_school_related_staff_cases: 5,
        new_school_related_unspecified_cases: 20,
        recent_total_school_related_cases: 795,
        recent_school_related_student_cases: 444,
        recent_school_related_staff_cases: 101,
        recent_school_related_unspecified_cases: 250,
        past_total_school_related_cases: 846,
        past_school_related_student_cases: 476,
        past_school_related_staff_cases: 140,
        past_school_related_unspecified_cases: 230,
        cumulative_school_related_cases: 1641,
        cumulative_school_related_student_cases: 920,
        cumulative_school_related_staff_cases: 241,
        cumulative_school_related_unspecified_cases: 480,
      },
      {
        _id: 30,
        collected_date: "2020-10-22T00:00:00",
        reported_date: "2020-10-23T00:00:00",
        current_schools_w_cases: 514,
        current_schools_closed: 4,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 72,
        new_school_related_student_cases: 39,
        new_school_related_staff_cases: 6,
        new_school_related_unspecified_cases: 27,
        recent_total_school_related_cases: 796,
        recent_school_related_student_cases: 440,
        recent_school_related_staff_cases: 95,
        recent_school_related_unspecified_cases: 261,
        past_total_school_related_cases: 902,
        past_school_related_student_cases: 506,
        past_school_related_staff_cases: 150,
        past_school_related_unspecified_cases: 246,
        cumulative_school_related_cases: 1698,
        cumulative_school_related_student_cases: 946,
        cumulative_school_related_staff_cases: 245,
        cumulative_school_related_unspecified_cases: 507,
      },
      {
        _id: 31,
        collected_date: "2020-10-23T00:00:00",
        reported_date: "2020-10-26T00:00:00",
        current_schools_w_cases: 548,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 72,
        new_school_related_student_cases: 39,
        new_school_related_staff_cases: 4,
        new_school_related_unspecified_cases: 29,
        recent_total_school_related_cases: 866,
        recent_school_related_student_cases: 477,
        recent_school_related_staff_cases: 99,
        recent_school_related_unspecified_cases: 290,
        past_total_school_related_cases: 904,
        past_school_related_student_cases: 508,
        past_school_related_staff_cases: 150,
        past_school_related_unspecified_cases: 246,
        cumulative_school_related_cases: 1770,
        cumulative_school_related_student_cases: 985,
        cumulative_school_related_staff_cases: 249,
        cumulative_school_related_unspecified_cases: 536,
      },
      {
        _id: 32,
        collected_date: "2020-10-26T00:00:00",
        reported_date: "2020-10-27T00:00:00",
        current_schools_w_cases: 593,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 144,
        new_school_related_student_cases: 82,
        new_school_related_staff_cases: 12,
        new_school_related_unspecified_cases: 50,
        recent_total_school_related_cases: 932,
        recent_school_related_student_cases: 503,
        recent_school_related_staff_cases: 103,
        recent_school_related_unspecified_cases: 326,
        past_total_school_related_cases: 978,
        past_school_related_student_cases: 560,
        past_school_related_staff_cases: 158,
        past_school_related_unspecified_cases: 260,
        cumulative_school_related_cases: 1910,
        cumulative_school_related_student_cases: 1063,
        cumulative_school_related_staff_cases: 261,
        cumulative_school_related_unspecified_cases: 586,
      },
      {
        _id: 33,
        collected_date: "2020-10-27T00:00:00",
        reported_date: "2020-10-28T00:00:00",
        current_schools_w_cases: 595,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 92,
        new_school_related_student_cases: 40,
        new_school_related_staff_cases: 13,
        new_school_related_unspecified_cases: 39,
        recent_total_school_related_cases: 938,
        recent_school_related_student_cases: 499,
        recent_school_related_staff_cases: 107,
        recent_school_related_unspecified_cases: 332,
        past_total_school_related_cases: 1063,
        past_school_related_student_cases: 604,
        past_school_related_staff_cases: 167,
        past_school_related_unspecified_cases: 292,
        cumulative_school_related_cases: 2001,
        cumulative_school_related_student_cases: 1103,
        cumulative_school_related_staff_cases: 274,
        cumulative_school_related_unspecified_cases: 624,
      },
      {
        _id: 34,
        collected_date: "2020-10-28T00:00:00",
        reported_date: "2020-10-29T00:00:00",
        current_schools_w_cases: 581,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 99,
        new_school_related_student_cases: 55,
        new_school_related_staff_cases: 9,
        new_school_related_unspecified_cases: 35,
        recent_total_school_related_cases: 923,
        recent_school_related_student_cases: 493,
        recent_school_related_staff_cases: 100,
        recent_school_related_unspecified_cases: 330,
        past_total_school_related_cases: 1175,
        past_school_related_student_cases: 664,
        past_school_related_staff_cases: 183,
        past_school_related_unspecified_cases: 328,
        cumulative_school_related_cases: 2098,
        cumulative_school_related_student_cases: 1157,
        cumulative_school_related_staff_cases: 283,
        cumulative_school_related_unspecified_cases: 658,
      },
      {
        _id: 35,
        collected_date: "2020-10-29T00:00:00",
        reported_date: "2020-10-30T00:00:00",
        current_schools_w_cases: 551,
        current_schools_closed: 0,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 61,
        new_school_related_student_cases: 40,
        new_school_related_staff_cases: 4,
        new_school_related_unspecified_cases: 17,
        recent_total_school_related_cases: 889,
        recent_school_related_student_cases: 481,
        recent_school_related_staff_cases: 91,
        recent_school_related_unspecified_cases: 317,
        past_total_school_related_cases: 1270,
        past_school_related_student_cases: 716,
        past_school_related_staff_cases: 196,
        past_school_related_unspecified_cases: 358,
        cumulative_school_related_cases: 2159,
        cumulative_school_related_student_cases: 1197,
        cumulative_school_related_staff_cases: 287,
        cumulative_school_related_unspecified_cases: 675,
      },
      {
        _id: 36,
        collected_date: "2020-10-30T00:00:00",
        reported_date: "2020-11-02T00:00:00",
        current_schools_w_cases: 558,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 69,
        new_school_related_student_cases: 41,
        new_school_related_staff_cases: 6,
        new_school_related_unspecified_cases: 22,
        recent_total_school_related_cases: 890,
        recent_school_related_student_cases: 480,
        recent_school_related_staff_cases: 86,
        recent_school_related_unspecified_cases: 324,
        past_total_school_related_cases: 1338,
        past_school_related_student_cases: 758,
        past_school_related_staff_cases: 207,
        past_school_related_unspecified_cases: 373,
        cumulative_school_related_cases: 2228,
        cumulative_school_related_student_cases: 1238,
        cumulative_school_related_staff_cases: 293,
        cumulative_school_related_unspecified_cases: 697,
      },
      {
        _id: 37,
        collected_date: "2020-11-02T00:00:00",
        reported_date: "2020-11-03T00:00:00",
        current_schools_w_cases: 578,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 134,
        new_school_related_student_cases: 82,
        new_school_related_staff_cases: 13,
        new_school_related_unspecified_cases: 39,
        recent_total_school_related_cases: 923,
        recent_school_related_student_cases: 505,
        recent_school_related_staff_cases: 79,
        recent_school_related_unspecified_cases: 339,
        past_total_school_related_cases: 1437,
        past_school_related_student_cases: 813,
        past_school_related_staff_cases: 227,
        past_school_related_unspecified_cases: 397,
        cumulative_school_related_cases: 2360,
        cumulative_school_related_student_cases: 1318,
        cumulative_school_related_staff_cases: 306,
        cumulative_school_related_unspecified_cases: 736,
      },
      {
        _id: 38,
        collected_date: "2020-11-03T00:00:00",
        reported_date: "2020-11-04T00:00:00",
        current_schools_w_cases: 581,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 116,
        new_school_related_student_cases: 81,
        new_school_related_staff_cases: 7,
        new_school_related_unspecified_cases: 28,
        recent_total_school_related_cases: 907,
        recent_school_related_student_cases: 527,
        recent_school_related_staff_cases: 76,
        recent_school_related_unspecified_cases: 304,
        past_total_school_related_cases: 1569,
        past_school_related_student_cases: 872,
        past_school_related_staff_cases: 237,
        past_school_related_unspecified_cases: 460,
        cumulative_school_related_cases: 2476,
        cumulative_school_related_student_cases: 1399,
        cumulative_school_related_staff_cases: 313,
        cumulative_school_related_unspecified_cases: 764,
      },
      {
        _id: 39,
        collected_date: "2020-11-04T00:00:00",
        reported_date: "2020-11-05T00:00:00",
        current_schools_w_cases: 580,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 68,
        new_school_related_student_cases: 37,
        new_school_related_staff_cases: 7,
        new_school_related_unspecified_cases: 24,
        recent_total_school_related_cases: 897,
        recent_school_related_student_cases: 512,
        recent_school_related_staff_cases: 78,
        recent_school_related_unspecified_cases: 307,
        past_total_school_related_cases: 1646,
        past_school_related_student_cases: 923,
        past_school_related_staff_cases: 242,
        past_school_related_unspecified_cases: 481,
        cumulative_school_related_cases: 2543,
        cumulative_school_related_student_cases: 1435,
        cumulative_school_related_staff_cases: 320,
        cumulative_school_related_unspecified_cases: 788,
      },
      {
        _id: 40,
        collected_date: "2020-11-05T00:00:00",
        reported_date: "2020-11-06T00:00:00",
        current_schools_w_cases: 582,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 85,
        new_school_related_student_cases: 49,
        new_school_related_staff_cases: 8,
        new_school_related_unspecified_cases: 28,
        recent_total_school_related_cases: 914,
        recent_school_related_student_cases: 525,
        recent_school_related_staff_cases: 81,
        recent_school_related_unspecified_cases: 308,
        past_total_school_related_cases: 1714,
        past_school_related_student_cases: 959,
        past_school_related_staff_cases: 247,
        past_school_related_unspecified_cases: 508,
        cumulative_school_related_cases: 2628,
        cumulative_school_related_student_cases: 1484,
        cumulative_school_related_staff_cases: 328,
        cumulative_school_related_unspecified_cases: 816,
      },
      {
        _id: 41,
        collected_date: "2020-11-06T00:00:00",
        reported_date: "2020-11-09T00:00:00",
        current_schools_w_cases: 565,
        current_schools_closed: 1,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 79,
        new_school_related_student_cases: 39,
        new_school_related_staff_cases: 13,
        new_school_related_unspecified_cases: 27,
        recent_total_school_related_cases: 906,
        recent_school_related_student_cases: 513,
        recent_school_related_staff_cases: 87,
        recent_school_related_unspecified_cases: 306,
        past_total_school_related_cases: 1801,
        past_school_related_student_cases: 1010,
        past_school_related_staff_cases: 254,
        past_school_related_unspecified_cases: 537,
        cumulative_school_related_cases: 2707,
        cumulative_school_related_student_cases: 1523,
        cumulative_school_related_staff_cases: 341,
        cumulative_school_related_unspecified_cases: 843,
      },
      {
        _id: 42,
        collected_date: "2020-11-09T00:00:00",
        reported_date: "2020-11-10T00:00:00",
        current_schools_w_cases: 601,
        current_schools_closed: 3,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 159,
        new_school_related_student_cases: 103,
        new_school_related_staff_cases: 23,
        new_school_related_unspecified_cases: 33,
        recent_total_school_related_cases: 936,
        recent_school_related_student_cases: 547,
        recent_school_related_staff_cases: 98,
        recent_school_related_unspecified_cases: 291,
        past_total_school_related_cases: 1929,
        past_school_related_student_cases: 1079,
        past_school_related_staff_cases: 265,
        past_school_related_unspecified_cases: 585,
        cumulative_school_related_cases: 2865,
        cumulative_school_related_student_cases: 1626,
        cumulative_school_related_staff_cases: 363,
        cumulative_school_related_unspecified_cases: 876,
      },
      {
        _id: 43,
        collected_date: "2020-11-10T00:00:00",
        reported_date: "2020-11-11T00:00:00",
        current_schools_w_cases: 654,
        current_schools_closed: 2,
        current_total_number_schools: 4828,
        new_total_school_related_cases: 198,
        new_school_related_student_cases: 116,
        new_school_related_staff_cases: 21,
        new_school_related_unspecified_cases: 61,
        recent_total_school_related_cases: 1033,
        recent_school_related_student_cases: 616,
        recent_school_related_staff_cases: 104,
        recent_school_related_unspecified_cases: 313,
        past_total_school_related_cases: 2030,
        past_school_related_student_cases: 1127,
        past_school_related_staff_cases: 279,
        past_school_related_unspecified_cases: 624,
        cumulative_school_related_cases: 3063,
        cumulative_school_related_student_cases: 1743,
        cumulative_school_related_staff_cases: 383,
        cumulative_school_related_unspecified_cases: 937,
      },
    ],
    limit: 1000,
    _links: {
      start:
        "/api/3/action/datastore_search?limit=1000&resource_id=7fbdbb48-d074-45d9-93cb-f7de58950418",
      next:
        "/api/3/action/datastore_search?offset=1000&limit=1000&resource_id=7fbdbb48-d074-45d9-93cb-f7de58950418",
    },
    total: 43,
  },
};

function collectedDates() {
  let arrayLength = schoolSummaryData.result.records.length;
  let results = [];
  for (let i = 0; i < arrayLength; i++) {
    results.push(
      schoolSummaryData.result.records[i].collected_date.slice(0, 10)
    );
  }
  return results;
}
console.log(collectedDates());

function currentSchoolsWithCases() {
  let arrayLength = schoolSummaryData.result.records.length;
  let results = [];
  for (let i = 0; i < arrayLength; i++) {
    results.push(schoolSummaryData.result.records[i].current_schools_w_cases);
  }
  return results;
}

function newSchoolRelatedCases() {
  let arrayLength = schoolSummaryData.result.records.length;
  let results = [];
  for (let i = 0; i < arrayLength; i++) {
    results.push(
      schoolSummaryData.result.records[i].new_total_school_related_cases
    );
  }
  return results;
}
console.log(newSchoolRelatedCases());
